---
version: '3.8'

networks:
  formance:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  postgres:
    image: "postgres:15-alpine"
    hostname: postgres
    container_name: postgres
    command:
      - -c
      - max_connections=200
    environment:
      POSTGRES_USER: "ledger"
      POSTGRES_PASSWORD: "ledger"
      POSTGRES_DB: "ledger"
      PGDATA: /data/postgres
    volumes:
      - ./volumes/database:/data/postgres
    networks:
      formance:
        ipv4_address: 10.0.0.16

  ledger:
    image: "ghcr.io/formancehq/ledger:v2.0.0-rc.20"
    hostname: ledger
    container_name: ledger
    environment:
      STORAGE_DRIVER: "postgres"
      POSTGRES_URI: "postgresql://ledger:ledger@10.0.0.16:5432/ledger?sslmode=disable"
      DEBUG: "true"
      BIND: ":8080"
    networks:
      formance:
        ipv4_address: 10.0.0.17

  workload:
    image: "us-central1-docker.pkg.dev/molten-verve-216720/formance-repository/workload"
    hostname: workload
    container_name: workload
    networks:
      formance:
        ipv4_address: 10.0.0.18
